apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
    - http:
        paths:
          - path: /ingredients
            pathType: Prefix
            backend:
              service:
                name: ing-srv
                port:
                  number: 80

          - path: /rec
            pathType: Prefix
            backend:
              service:
                name: rec-srv
                port:
                  number: 80
